title: My blog - Rémi Canard
email: remi.cnrd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Rémi Canard's blog, focusing on sharing Data Sciences discoveries and recent learnings. Enjoy!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Rémi Canard # add your name
author-pic: remi-picture.jpg
about-author: My name is Rémi Canard. I’m a Computer Science graduate engineer, currently MSc student in Data Sciences @ CentraleSupélec & Essec and Data Scientist @ ProcessOut, check us out!

# Contact links
email: remi.canard@essec.edu
phone: # Add your Phone number
website: remicnrd.github.io./
linkedin: remicanard
github: remicnrd # Add your Github handle
twitter: # Add your Twitter handle
facebook: remi.canard.7
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
